name: islamic_guidance
description: تطبيق إسلامي شامل للقرآن والصلاة والأذكار
publish_to: 'none'
version: 2.0.0+200

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # State Management
  flutter_bloc: ^8.1.3
  provider: ^6.1.1
  
  # Notifications
  flutter_local_notifications: ^16.3.0
  timezone: ^0.9.2
  
  # Location
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  
  # Sensors
  sensors_plus: ^4.0.2
  flutter_compass: ^0.8.0
  
  # Audio
  just_audio: ^0.9.36
  audio_session: ^0.1.18
  
  # Network
  dio: ^5.4.0
  http: ^1.1.0
  connectivity_plus: ^5.0.2
  
  # UI
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  
  # Utilities
  intl: ^0.19.0
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  device_info_plus: ^9.1.1
  package_info_plus: ^5.0.1
  share_plus: ^7.2.1
  url_launcher: ^6.2.2
  
  # Islamic Calculations
  adhan: ^2.0.0+1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/audio/
    - assets/fonts/
  
  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
        - asset: assets/fonts/Amiri-Bold.ttf
          weight: 700
    - family: Scheherazade
      fonts:
        - asset: assets/fonts/ScheherazadeNew-Regular.ttf
        - asset: assets/fonts/ScheherazadeNew-Bold.ttf
          weight: 700
